  
# 核心任务

- name: xwiki
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml
  
  vars_prompt:
    - name: 'xwiki_selection'
      prompt: "Choose the xwiki distribution \n
      1: xwiki 5 Classic\n
      2: xwiki Artemis\n"
      private: no
      default: 1

  vars:
    xwiki_select:
      '1': "classic"
      '2': "artemis"

    xwiki_distribution: "{{xwiki_select[xwiki_selection]}}"
  
  pre_tasks:
    - debug:
        msg: Will install {{xwiki_distribution}}

  roles:
    - {role: role_common, tags: "role_common"}  
    - {role: role_cloud, tags: "role_cloud"}  
    - {role: role_jdk, tags: "role_jdk"}  
    - {role: xwiki, tags: "xwiki"}
    - {role: role_preend, tags: "preend"}
    - {role: role_end, tags: "role_end"}
