  
# 核心任务

- name: xwiki
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml
  
  

  roles:
    - {role: role_common, tags: "role_common"}  
    - {role: role_jdk, tags: "role_jdk"}  
    - {role: xwiki, tags: "xwiki"}
    - {role: role_preend, tags: "preend"}
    - {role: role_end, tags: "role_end"}
