# install xwiki by OS_family
# installation is same on different OS

- name: Add directory /usr/local/xwiki
  file:
    path: /usr/local/
    state: directory
    owner: root    
    group: root
    mode: '0750'
    

    
- name: Remove extra dir for re-installation
  shell: rm -rf /usr/local/xwiki*
  
- name: Download xwiki
  unarchive:
    src: "{{xwiki_download_url}}"
    dest: /usr/local
    remote_src: yes
    owner: root
    group: root
    
- name: Remove extra dir for re-installation
  shell: 
         cd /usr/local/
         unzip  xwiki-platform-distribution-jetty-hsqldb-12.3.zip



# configure xwiki

- name: Setting xwiki service
  copy:
    src: xwiki.service
    dest: /lib/systemd/system/xwiki.service

- name: Start and enable xwiki
  service:
    name: xwiki.service
    state: restarted
    enabled: yes

# set soft link, -b cover the exist links
# ln -sb src des
- name: set soft link
  shell: |
    ln -sb /usr/local/xwiki  /data/wwwroot/xwiki
    ln -sb /var/lib/xwiki/data  /data/logs/xwiki
    ln -sb /usr/local/xwiki-platform-distribution-jetty-hsqldb-12.3/webapps/xwiki/WEB-INF/xwiki.cfg  /data/config/xwiki
# Check version,
# must use sudo sh -c to solve the no-root permission
- block:
  - name: Check xwiki Version
    shell: sudo sh -c 'echo  xwiki $(cat /usr/local/xwiki-platform-distribution-jetty-hsqldb-12.3/webapps/xwiki/WEB-INF/version.properties | sed -n 1p)" 1>> /data/logs/install_version.txt'

# check service state
- name: Check xwiki Service
  shell: systemctl status xwiki | grep Active*
  register: check xwiki_service
  notify: check xwiki_service